# Generated by Django 5.1.5 on 2025-01-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_submission',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='submission_to_database',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='withdrawal_from_bases',
            field=models.DateTimeField(),
        ),
    ]
