# Generated by Django 5.1.5 on 2025-01-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_record_date_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_delivery',
            field=models.DateTimeField(),
        ),
    ]
