# Generated by Django 5.1.5 on 2025-01-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_record_date_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='record',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
