# Generated by Django 5.1.5 on 2025-01-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_record_file3_record_file4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
