# Generated by Django 5.1.5 on 2025-01-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_record_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='delivery',
            field=models.IntegerField(default=5),
        ),
    ]
