# Generated by Django 5.1.5 on 2025-02-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_record_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='delivery',
        ),
    ]
